# Generated by Django 2.2.28 on 2022-05-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220417_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ppassword',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
